eureka:
  client:
  serviceUrl: http://eureka-server:8761/eureka/   #http://${eureka.instance.hostname}:${server.port}/eureka/


server:
  port: 8762
spring:
  application:
    name: service-zuul
zuul:
  routes:
    hiapi:
      path: /hiapi/**
      serviceId: eureka-client
    feignapi:
      path: /feignapi/**
      serviceId: eureka-feign-client
  prefix: /v1
